include ../config.mk

# use a project-local hardware definition file

# HD44780 character LCD PMOD on PMOD A/B:
PRFLAGS += -ccf src/gm-proto-e1.ccf

# HD44780 character LCD soldered on GM-PROTO-E1:
#PRFLAGS += -ccf src/gm-proto-e1.ccf

TOP = display
